### ISSUE TITLE
Can not be installed together with `pulumi==3.104` (required for python 3.12)

### ISSUE THREAD

**Issue by estyrke** [pulumi/pulumi-policy#334]
### What happened?

I am using Poetry to install dependencies. Because of https://github.com/grpc/grpc/issues/34853, the main pulumi package was updated to use grpcio 1.60. Since pulumi-policy is pinned to grpcio 1.56, Poetry can't install them together:

```
~/C/a/i/test ❯❯❯ poetry install
Updating dependencies
Resolving dependencies... (1.0s)

    Because no versions of pulumi-policy match >1.9.0,<1.10.0a1704644388 || >1.10.0a1704644388,<1.10.0a1706538348 || >1.10.0a1706538348,<2.0.0
 and pulumi-policy (1.10.0a1704644388) depends on grpcio (1.56.2), pulumi-policy (>1.9.0,<1.10.0a1706538348 || >1.10.0a1706538348,<2.0.0) requires grpcio (1.56.2).
(1) So, because pulumi-policy (1.10.0a1706538348) depends on grpcio (1.56.2)
 and pulumi-policy (1.9.0) depends on grpcio (1.56.2), pulumi-policy (>=1.9.0,<2.0.0) requires grpcio (1.56.2).

    Because no versions of pulumi match >3.103.0,<3.103.1 || >3.103.1,<3.104.0 || >3.104.0,<3.104.1 || >3.104.1,<3.104.2 || >3.104.2,<3.105.0 || >3.105.0,<4.0.0
 and pulumi (3.103.0) depends on grpcio (>=1.60.0,<1.61.0), pulumi (>=3.103.0,<3.103.1 || >3.103.1,<3.104.0 || >3.104.0,<3.104.1 || >3.104.1,<3.104.2 || >3.104.2,<3.105.0 || >3.105.0,<4.0.0) requires grpcio (>=1.60.0,<1.61.0).
    And because pulumi (3.103.1) depends on grpcio (>=1.60.0,<1.61.0), pulumi (>=3.103.0,<3.104.0 || >3.104.0,<3.104.1 || >3.104.1,<3.104.2 || >3.104.2,<3.105.0 || >3.105.0,<4.0.0) requires grpcio (>=1.60.0,<1.61.0).
    And because pulumi (3.104.0) depends on grpcio (>=1.60.0,<1.61.0)
 and pulumi (3.104.1) depends on grpcio (>=1.60.0,<1.61.0), pulumi (>=3.103.0,<3.104.2 || >3.104.2,<3.105.0 || >3.105.0,<4.0.0) requires grpcio (>=1.60.0,<1.61.0).
    And because pulumi (3.104.2) depends on grpcio (>=1.60.0,<1.61.0)
 and pulumi (3.105.0) depends on grpcio (>=1.60.1,<1.61.0), pulumi (>=3.103.0,<4.0.0) requires grpcio (>=1.60.0,<1.61.0).
    And because pulumi-policy (>=1.9.0,<2.0.0) requires grpcio (1.56.2) (1), pulumi-policy (>=1.9.0,<2.0.0) is incompatible with pulumi (>=3.103.0,<4.0.0)
    So, because my-package depends on both pulumi (^3.103.0) and pulumi-policy (^1.9.0), version solving failed.
```

### Example

pyproject.toml:

```toml
[tool.poetry]
name = "my-package"
version = "0.1.0"
description = "Desc"
authors = ["Emil Styrke <emil.styrke@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pulumi = "^3.103.0"
pulumi-policy = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Output of `pulumi about`

```
CLI          
Version      3.104.2
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host     
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in python: executable='/Users/emil/Code/arbo-infra/infra/test/.venv/bin/python3' version='3.12.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
